sudo: required

services:
    docker
    
script:
  - echo "building"

deploy:
  provider: script
  script: bash build shock01/stefhock-hugo $DOCKER_USERNAME $DOCKER_PASSWORD
  skip-cleanup: true
  on:
    branch: master
 
after_deploy:
    - ./trigger_travis.sh shock01 stefhock.nl $TRAVIS_ACCESS_TOKEN "trigger for update theme"    
