#!/usr/bin/env bash

set -ev

if [ "$#" -ne 3 ]; then
  echo "Usage: <docker_repo> <docker_username> <docker_password>" >&2
  exit 1
fi

repo=$1
username=$2
password=$3

docker login -u"$username" -p"$password"
docker build --no-cache -t $repo:latest . 
docker push $repo