# theme.toml template for a Hugo theme

name = "stefhock.nl theme"
license = "MIT"
description = "Stef Hock default theme"
tags = ["website", "stefhock.nl", "responsive"]
min_version = 0.30.2

[author]
  name = "Stef Hock"
  homepage = "https://www.stefhock.nl"
